timezone_clock.admin_settings:
  type: config_object
  label: 'Timezone Clock Admin Settings'
  mapping:
    country:
      type: string
      label: 'Country'
    city:
      type: string
      label: 'City'
    timezone:
      type: string
      label: 'Timezone'
