<?php
/**
 * Implements hook_preprocess_HOOK() for block templates.
 */
function site_location_time_preprocess_block(&$variables) {
  // Check if this is your custom block.
  if ($variables['elements']['#id'] == 'site_location_time_custom_block') {
    // Add the block content to a variable.
    $block_content = \Drupal::service('renderer')->renderRoot($variables['elements']);
    // Pass the block content to the template.
    $variables['custom_block_content'] = $block_content;
  }
}
